workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
      node: 22
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Setup iOS project
        script: |
          # Remove existing iOS project and regenerate
          rm -rf ios
          npx cap add ios
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -resolvePackageDependencies -project App.xcodeproj -scheme App
          xcodebuild build -project App.xcodeproj \
            -scheme App \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/App/build/**/*.app
      - ios/App/build/**/*.ipa

  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-21-openjdk-amd64
      node: 22
      java: 21
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Update Android project
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
